name: flutter_hive_test
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  flutter_secure_storage: ^5.0.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8

  flutter_lints: ^1.0.0


flutter:

   uses-material-design: true

 
   assets:
    - images/image.jpg
  
