name: MainFlow

on:
  push:
    branches: [ main ]

jobs:
 build:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v2
     - uses: subosito/flutter-action@v2
     - run: flutter build windows
     - uses: actions/upload-artifact@v1
        with:
          name: release-exe
          path: build/windows/runner/Release/app-release.exe
         